import { IUser } from './types';

const users: IUser[] = [
  {
    _id: '6166e7ecfd5d1f95f1fb4b41',
    index: 0,
    guid: '42701bc2-e813-4d78-969b-2281b590e52d',
    isActive: true,
    balance: '$3,011.81',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'blue',
    name: 'Burnett Rush',
    gender: 'male',
    company: 'SENSATE',
    email: 'burnettrush@sensate.com',
    phone: '+1 (921) 599-3770',
    address: '805 Suydam Place, Crucible, Federated States Of Micronesia, 211',
    tags: ['pariatur', 'elit', 'do', 'ex', 'ut', 'ad', 'duis'],
    friends: [
      {
        id: 0,
        name: 'Lara Cole',
      },
      {
        id: 1,
        name: 'Vazquez Cabrera',
      },
      {
        id: 2,
        name: 'Monica Fernandez',
      },
    ],
    favoriteFruit: 'banana',
  },
  {
    _id: '6166e7ecd2f41d4158296512',
    index: 1,
    guid: '378fe892-72db-4f2d-921d-f3fa8ca90b03',
    isActive: true,
    balance: '$1,614.23',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'blue',
    name: 'Saundra Burks',
    gender: 'female',
    company: 'INJOY',
    email: 'saundraburks@injoy.com',
    phone: '+1 (948) 523-3047',
    address: '857 Keap Street, Shindler, Connecticut, 2174',
    tags: ['deserunt', 'commodo', 'magna', 'deserunt', 'in', 'cillum', 'non'],
    friends: [
      {
        id: 0,
        name: 'Lindsay Mcpherson',
      },
      {
        id: 1,
        name: 'Olson Johns',
      },
      {
        id: 2,
        name: 'Larson Mccormick',
      },
    ],
    favoriteFruit: 'banana',
  },
  {
    _id: '6166e7ec61338c64a0fa1de7',
    index: 2,
    guid: '254560bd-d02b-4241-b70d-720b12f517bb',
    isActive: false,
    balance: '$2,887.79',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'brown',
    name: 'Callie Bauer',
    gender: 'female',
    company: 'OPTICALL',
    email: 'calliebauer@opticall.com',
    phone: '+1 (819) 476-2565',
    address: '717 Friel Place, Sheatown, Maine, 7505',
    tags: [
      'aute',
      'minim',
      'voluptate',
      'proident',
      'aliquip',
      'commodo',
      'laborum',
    ],
    friends: [
      {
        id: 0,
        name: 'Gabriela Bird',
      },
      {
        id: 1,
        name: 'Hyde Murphy',
      },
      {
        id: 2,
        name: 'Tommie Ross',
      },
    ],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6166e7ecfef3f96cb35e61e2',
    index: 3,
    guid: 'acffebd1-0146-4a7a-9b8f-9f8c8bf03cd7',
    isActive: false,
    balance: '$1,392.27',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'green',
    name: 'Alma Martin',
    gender: 'female',
    company: 'KLUGGER',
    email: 'almamartin@klugger.com',
    phone: '+1 (953) 497-2741',
    address: '472 Loring Avenue, Clarktown, Iowa, 4365',
    tags: ['duis', 'aliquip', 'aliqua', 'sit', 'enim', 'sit', 'fugiat'],
    friends: [
      {
        id: 0,
        name: 'Perry Barber',
      },
      {
        id: 1,
        name: 'Sybil Johnson',
      },
      {
        id: 2,
        name: 'Thompson Sampson',
      },
    ],
    favoriteFruit: 'orange',
  },
  {
    _id: '6166e7ec3ea64fe0ec70554f',
    index: 4,
    guid: '1f618e9a-2fc9-4276-a3fe-50d1c144f039',
    isActive: true,
    balance: '$3,879.30',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'green',
    name: 'Sanford Ellison',
    gender: 'male',
    company: 'SENMEI',
    email: 'sanfordellison@senmei.com',
    phone: '+1 (863) 492-3560',
    address: '716 Wyona Street, Lindisfarne, Maryland, 4430',
    tags: ['nisi', 'ea', 'exercitation', 'ad', 'eu', 'aliqua', 'eu'],
    friends: [
      {
        id: 0,
        name: 'Georgina George',
      },
      {
        id: 1,
        name: 'Carver Valdez',
      },
      {
        id: 2,
        name: 'Angelica Beasley',
      },
    ],
    favoriteFruit: 'apple',
  },
  {
    _id: '6166e7eccbbda17adff065bb',
    index: 5,
    guid: '6e73eb13-409f-4169-b21b-267ceefa3156',
    isActive: true,
    balance: '$3,944.48',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'blue',
    name: 'Rosanna Randall',
    gender: 'female',
    company: 'APEXTRI',
    email: 'rosannarandall@apextri.com',
    phone: '+1 (893) 431-2201',
    address: '692 Leonora Court, Fulford, Ohio, 6236',
    tags: [
      'Lorem',
      'proident',
      'incididunt',
      'deserunt',
      'excepteur',
      'consequat',
      'nisi',
    ],
    friends: [
      {
        id: 0,
        name: 'Suzette Hester',
      },
      {
        id: 1,
        name: 'Rosalinda Hatfield',
      },
      {
        id: 2,
        name: 'Kramer Montgomery',
      },
    ],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6166e7ec8aecd93c56ebd0ec',
    index: 6,
    guid: '9935030e-e278-45dc-97ad-e2aaabe085cd',
    isActive: false,
    balance: '$2,150.89',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'blue',
    name: 'Chelsea Webb',
    gender: 'female',
    company: 'NEUROCELL',
    email: 'chelseawebb@neurocell.com',
    phone: '+1 (830) 488-2037',
    address: '287 Saratoga Avenue, Gwynn, Puerto Rico, 8354',
    tags: [
      'ipsum',
      'occaecat',
      'esse',
      'reprehenderit',
      'culpa',
      'fugiat',
      'voluptate',
    ],
    friends: [
      {
        id: 0,
        name: 'Cleo Parks',
      },
      {
        id: 1,
        name: 'Christie Moran',
      },
      {
        id: 2,
        name: 'Jeri Dixon',
      },
    ],
    favoriteFruit: 'banana',
  },
  {
    _id: '6166e7ec24805b7e5b74ca19',
    index: 7,
    guid: 'f7ec9978-49e8-453d-9f07-a252e4aa41b1',
    isActive: false,
    balance: '$3,152.45',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'brown',
    name: 'Crawford Middleton',
    gender: 'male',
    company: 'ROCKYARD',
    email: 'crawfordmiddleton@rockyard.com',
    phone: '+1 (962) 489-3088',
    address: '898 Noll Street, Bethpage, Michigan, 1854',
    tags: ['cillum', 'ea', 'ad', 'duis', 'laborum', 'nisi', 'qui'],
    friends: [
      {
        id: 0,
        name: 'Kirk Lowe',
      },
      {
        id: 1,
        name: 'Dillard Small',
      },
      {
        id: 2,
        name: 'Bertha Barry',
      },
    ],
    favoriteFruit: 'banana',
  },
  {
    _id: '6166e7ec330ff973a0283b8c',
    index: 8,
    guid: 'de7c6944-5ebe-414c-b5b9-1f7ec290e6b3',
    isActive: true,
    balance: '$2,550.83',
    picture: 'http://placehold.it/32x32',
    age: 22,
    eyeColor: 'blue',
    name: 'Paul Padilla',
    gender: 'male',
    company: 'ECSTASIA',
    email: 'paulpadilla@ecstasia.com',
    phone: '+1 (813) 510-3961',
    address: '868 Vermont Court, Sunriver, Florida, 8466',
    tags: ['ut', 'consectetur', 'officia', 'cillum', 'non', 'irure', 'Lorem'],
    friends: [
      {
        id: 0,
        name: 'Irwin Cervantes',
      },
      {
        id: 1,
        name: 'Reynolds Gray',
      },
      {
        id: 2,
        name: 'Veronica Mckenzie',
      },
    ],
    favoriteFruit: 'apple',
  },
  {
    _id: '6166e7ecefdc62ce5feffd94',
    index: 9,
    guid: '65fb6eb9-59b1-445d-bf89-d8840441c5b5',
    isActive: true,
    balance: '$2,054.19',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'green',
    name: 'Dixon Stout',
    gender: 'male',
    company: 'ORBOID',
    email: 'dixonstout@orboid.com',
    phone: '+1 (942) 594-3827',
    address: '732 Kay Court, Titanic, Marshall Islands, 4022',
    tags: [
      'laborum',
      'exercitation',
      'eiusmod',
      'ad',
      'in',
      'laborum',
      'ullamco',
    ],
    friends: [
      {
        id: 0,
        name: 'Alana Reilly',
      },
      {
        id: 1,
        name: 'Dodson Lowery',
      },
      {
        id: 2,
        name: 'Ernestine Whitney',
      },
    ],
    favoriteFruit: 'banana',
  },
  {
    _id: '6166e7ec79936ac62997120b',
    index: 10,
    guid: 'ef550dea-ba2e-4697-81ed-b2df2b63f9d7',
    isActive: false,
    balance: '$2,408.60',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'brown',
    name: 'Jackie Leblanc',
    gender: 'female',
    company: 'SYNKGEN',
    email: 'jackieleblanc@synkgen.com',
    phone: '+1 (900) 547-2978',
    address: '836 Nixon Court, Townsend, American Samoa, 1998',
    tags: ['laboris', 'et', 'do', 'ad', 'exercitation', 'nisi', 'velit'],
    friends: [
      {
        id: 0,
        name: 'Blair Weeks',
      },
      {
        id: 1,
        name: 'Boone Chen',
      },
      {
        id: 2,
        name: 'Ola Martinez',
      },
    ],
    favoriteFruit: 'apple',
  },
  {
    _id: '6166e7ec6ad2aa9b369fb952',
    index: 11,
    guid: 'dd75c3c6-6565-4802-bbae-cd2a883b2346',
    isActive: false,
    balance: '$2,429.87',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'green',
    name: 'Reyna Gross',
    gender: 'female',
    company: 'OVERFORK',
    email: 'reynagross@overfork.com',
    phone: '+1 (812) 464-3669',
    address: '211 Covert Street, Siglerville, Kentucky, 1207',
    tags: [
      'sit',
      'exercitation',
      'minim',
      'consequat',
      'officia',
      'ipsum',
      'proident',
    ],
    friends: [
      {
        id: 0,
        name: 'Hopper Greer',
      },
      {
        id: 1,
        name: 'Joyce Combs',
      },
      {
        id: 2,
        name: 'Goodwin Houston',
      },
    ],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6166e7ec3877da771ce251d4',
    index: 12,
    guid: 'dedf05a1-7b45-4a7d-acc6-f35698be5c76',
    isActive: false,
    balance: '$2,139.32',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'green',
    name: 'Blake Mccoy',
    gender: 'male',
    company: 'ZIDANT',
    email: 'blakemccoy@zidant.com',
    phone: '+1 (891) 458-2433',
    address: '515 Bay Street, Ernstville, Hawaii, 6550',
    tags: ['exercitation', 'officia', 'est', 'dolore', 'anim', 'sint', 'et'],
    friends: [
      {
        id: 0,
        name: 'Stuart Swanson',
      },
      {
        id: 1,
        name: 'Christian Wright',
      },
      {
        id: 2,
        name: 'Jordan Mcintosh',
      },
    ],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6166e7ec1de9d651db1987ec',
    index: 13,
    guid: 'b0d3fd78-0b6d-4337-af0f-f010a7ecbc5b',
    isActive: true,
    balance: '$3,338.74',
    picture: 'http://placehold.it/32x32',
    age: 35,
    eyeColor: 'green',
    name: 'Sellers Salazar',
    gender: 'male',
    company: 'FROSNEX',
    email: 'sellerssalazar@frosnex.com',
    phone: '+1 (886) 478-3777',
    address: '165 Fane Court, Fostoria, District Of Columbia, 6495',
    tags: ['qui', 'in', 'id', 'adipisicing', 'culpa', 'non', 'et'],
    friends: [
      {
        id: 0,
        name: 'Theresa Cotton',
      },
      {
        id: 1,
        name: 'Stevenson Berg',
      },
      {
        id: 2,
        name: 'Diana Oliver',
      },
    ],
    favoriteFruit: 'banana',
  },
  {
    _id: '6166e7ec0059edb4c266d713',
    index: 14,
    guid: 'c6322722-f784-48b2-919e-9e15adfc9a67',
    isActive: true,
    balance: '$1,051.87',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'blue',
    name: 'Marjorie Mckinney',
    gender: 'female',
    company: 'ACUSAGE',
    email: 'marjoriemckinney@acusage.com',
    phone: '+1 (977) 448-2931',
    address: '730 Hicks Street, Hebron, Minnesota, 4306',
    tags: [
      'exercitation',
      'duis',
      'anim',
      'exercitation',
      'velit',
      'in',
      'est',
    ],
    friends: [
      {
        id: 0,
        name: 'Nash Mitchell',
      },
      {
        id: 1,
        name: 'Araceli Durham',
      },
      {
        id: 2,
        name: 'Hays Long',
      },
    ],
    favoriteFruit: 'banana',
  },
];

export default users;
